# Generated by Django 3.2.7 on 2021-10-03 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_alter_funcionario_empresa'),
        ('registro_hora_extra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoraextra',
            name='funcionario',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario'),
        ),
        migrations.AlterField(
            model_name='registrohoraextra',
            name='motivo',
            field=models.CharField(max_length=100),
        ),
    ]
